demo/routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\OrderController;
use App\Http\Controllers\Admin\DashboardController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Client\PayPalController;

Route::get('/', [HomeController::class, 'index'])->name('client.home');
Route::get('/contact', [HomeController::class, 'contact'])->name('client.contact');


Route::get('product/{category_id}', [ClientProductController::class, 'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class, 'show'])->name('client.products.show');

Route::middleware('auth')->group(function(){

    Route::get('create-transaction', [PayPalController::class, 'createTransaction'])->name('createTransaction');
    Route::get('process-transaction', [PayPalController::class, 'processTransaction'])->name('processTransaction')->middleware('user.can_checkout_cart');
    Route::get('success-transaction', [PayPalController::class, 'successTransaction'])->name('successTransaction')->middleware('user.can_checkout_cart');
    Route::get('cancel-transaction', [PayPalController::class, 'cancelTransaction'])->name('cancelTransaction');

    Route::post('add-to-cart', [CartController::class, 'store'])->name('client.carts.add');
    Route::get('carts', [CartController::class, 'index'])->name('client.carts.index');
    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])->name('client.carts.update_product_quantity');
    Route::post('remove-product-in-cart/{cart_product_id}', [CartController::class, 'removeProductInCart'])->name('client.carts.remove_product');

    Route::post('apply-coupon', [CartController::class, 'applyCoupon'])->name('client.carts.apply_coupon');
    Route::get('checkout', [CartController::class, 'checkout'])->name('client.checkout.index')->middleware('user.can_checkout_cart');
    Route::get('process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.proccess')->middleware('user.can_checkout_cart');
    Route::get('list-orders', [OrderController::class, 'index'])->name('client.orders.index');
    Route::post('orders/cancel/{id}', [OrderController::class, 'cancel'])->name('client.orders.cancel');
});

Route::get('/dashboard', function () {
    return view('admin.dashboard.index');
})->name('dashboard');

Route::get('/home', function () {
    return view('client.layouts.app');
});

Auth::routes();

// route admin
Route::middleware('auth')->group(function(){

    Route::get('/dashboard', [DashboardController::class,'index'])->name('dashboard');
    // role
    Route::prefix('roles')->controller(RoleController::Class)->name('roles.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('role:super-admin');
        Route::post('/', 'store')->name('store')->middleware('role:super-admin');
        Route::get('/create', 'create')->name('create')->middleware('role:super-admin');
        Route::get('/{coupon}', 'show')->name('show')->middleware('role:super-admin');
        Route::put('/{coupon}', 'update')->name('update')->middleware('role:super-admin');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('role:super-admin');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('role:super-admin');
    });
    // user
    Route::prefix('users')->controller(UserController::Class)->name('users.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-user');
        Route::post('/', 'store')->name('store')->middleware('permission:create-user');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-user');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-user');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-user');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-user');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-user');
    });
    // category
    Route::prefix('categories')->controller(CategoryController::Class)->name('categories.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-category');
        Route::post('/', 'store')->name('store')->middleware('permission:create-category');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-category');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-category');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-category');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-category');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-category');
    });
    // product
    Route::prefix('products')->controller(ProductController::Class)->name('products.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-product');
        Route::post('/', 'store')->name('store')->middleware('permission:create-product');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-product');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-product');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-product');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-product');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-product');
    });
    //coupon
    Route::prefix('coupons')->controller(CouponController::Class)->name('coupons.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-coupon');
        Route::post('/', 'store')->name('store')->middleware('permission:create-coupon');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-coupon');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-coupon');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-coupon');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-coupon');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-coupon');
    });
    //order
    Route::get('orders', [AdminOrderController::class, 'index'])->name('admin.orders.index')->middleware('permission:list-order');
    Route::post('update-status/{id}', [AdminOrderController::class, 'updateStatus'])->name('admin.orders.update_status')->middleware('permission:list-order');
});

demo/app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\HandleImageTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use HasFactory, HandleImageTrait;

    protected $fillable = [
        'name',
        'description',
        'sale',
        'price'
    ];

    public function details()
    {
        return $this->hasMany(ProductDetail::class);
    }

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function assignCategory($categoryIds)
    {
        return $this->categories()->sync($categoryIds);
    }

    public function getBy($dataSearch, $categoryId)
    {
        return $this->whereHas('categories', fn ($q) => $q->where('category_id', $categoryId));
    }

    public function getImagePathAttribute()
    {
        return asset($this->images->count() > 0 ? 'upload/' . $this->images->first()->url : 'upload/default.jpg');
    }

    public function getSalePriceAttribute()
    {
        return $this->attributes['sale'] ? $this->attributes['price'] - ($this->attributes['sale'] * 0.01  * $this->attributes['price']) : 0;
    }
    public function scopeSearch($query)
    {
        if (request()->key) {
            $key = request()->key;
            $query->where('name', 'LIKE', '%' . $key . '%');
        }
        return $query;
    }

    public function scopeSize($query)
    {
        if (request()->size) {
            $query->whereHas('details', function ($query) {
                $query->whereIn('product_details.size', request()->size);
            });
        }
        return $query;
    }

    public function scopeSortBy($query)
    {
        if (request()->sort == "DESC") {
            $query->orderByRaw('(price - (price*sale/100)) desc');
        }
        if (request()->sort == "ASC") {
            $query->orderByRaw('(price - (price*sale/100)) asc');
        }
        return $query;
    }
}

demo/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Products\CreateProductRequest;
use App\Http\Requests\Products\UpdateProductRequest;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductDetail;
use Illuminate\Http\Request;


class ProductController extends Controller
{

    protected $category;
    protected $product;
    protected $productDetail;

    public function __construct(Product $product, Category $category, ProductDetail $productDetail)
    {
        $this->product = $product;
        $this->category = $category;
        $this->productDetail =  $productDetail;
    }

    public function index()
    {
        $products =  $this->product->latest('id')->paginate(4);
        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        $categories = $this->category->get(['id','name']);
        return view('admin.products.create', compact('categories'));
    }

    public function store(CreateProductRequest $request)
    {
        $dataCreate = $request->except('sizes');
        $sizes = $request->sizes ? json_decode($request->sizes) : [];
        $product = Product::create($dataCreate);
        $dataCreate['image'] = $this->product->saveImage($request);
        $product->images()->create(['url' => $dataCreate['image']]);
        $product->assignCategory($dataCreate['category_ids']);
        $sizeArray = [];
        foreach($sizes as $size)
        {
            $sizeArray[] = ['size' => $size->size, 'quantity' => $size->quantity, 'product_id' => $product->id];
        }
        $product->details()->insert($sizeArray);
        return redirect()->route('products.index')->with(['message' => 'Create  success']);
    }

    public function show($id)
    {
        $product =  $this->product->with(['details', 'categories'])->findOrFail($id);
        return view('admin.products.show', compact('product'));
    }

    public function edit($id)
    {
        $product =  $this->product->with(['details', 'categories'])->findOrFail($id);
        $categories = $this->category->get(['id','name']);
        return view('admin.products.edit', compact('categories', 'product'));
    }

    public function update(UpdateProductRequest $request, $id)
    {
        $dataUpdate = $request->except('sizes');
        $sizes = $request->sizes ? json_decode($request->sizes) : [];
        $product = $this->product->findOrFail($id);
        $currentImage =  $product->images ? $product->images->first()->url : '';
        $dataUpdate['image'] = $this->product->updateImage($request, $currentImage);
        $product->update($dataUpdate);
        $product->images()->delete();
        $product->images()->create(['url' => $dataUpdate['image']]);
        $product->assignCategory($dataUpdate['category_ids']);
        $sizeArray = [];
        foreach($sizes as $size)
        {
            $sizeArray[] = ['size' => $size->size, 'quantity' => $size->quantity, 'product_id' => $product->id];
        }
        $product->details()->delete($sizes);
        $product->details()->insert($sizeArray);
        return redirect()->route('products.index')->with(['message' => 'Update  success']);
    }

    public function destroy($id)
    {
        $product = $this->product->findOrFail($id);
        $product->delete();
        $product->details()->delete();
        $imageName =  $product->images->count() > 0 ? $product->images->first()->url : '';
        $this->product->deleteImage($imageName);
        return redirect()->route('products.index')->with(['message' => 'Delete  success']);
    }
}

demo/app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\ProductDetail;
use Illuminate\Http\Request;
use App\Models\Product;



class ProductController extends Controller
{

    protected $product;
    protected $productDetail;
    protected $category;
    public function __construct(Product $product,ProductDetail $productDetail,Category $category)
    {
        $this->product = $product;
        $this->productDetail = $productDetail;
        $this->category = $category;

    }

    public function index(Request $request, $category_id)
    {
        $categories=$this->category->all();
        $products =  $this->product->getBy($request->all(), $category_id)->Size()->Search()->SortBy()->paginate(6);
        $productDetails= $this->productDetail->select('size')->distinct()->get();
        return view('client.products.index', compact('products','productDetails','categories'));
    }

    public function show($id)
    {
        $product = $this->product->with('details')->findOrFail($id);
        return view('client.products.detail', compact('product'));

    }
}

demo/resources/views/admin/products/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create Product')
@section('content')
    <div class="card">
        <h2 style="text-align: center;padding:2px">Create Product</h2>
        <div>
            <form action="{{ route('products.store') }}" method="post" id="createForm" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class=" input-group-static col-5">
                        <label>Image</label>
                        <input type="file" accept="image/*" name="image" id="image-input" class="form-control">
                        @error('image')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>
                    <div class="col-5">
                        <img src="" id="show-image" alt="Product image" width="150px" height="150px">
                    </div>
                </div>
                <div class="input-group input-group-static ">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') }}" name="name" class="form-control">

                    @error('name')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <div class="input-group input-group-static">
                    <label>Price</label>
                    <input type="number" step="0.1" value="{{ old('price') }}" name="price" class="form-control">
                    @error('price')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <div class="input-group input-group-static ">
                    <label>Sale</label>
                    <input type="number" value="0" max="50" min="0" value="{{ old('sale') }}" name="sale" class="form-control">
                    @error('sale')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <div class="description">
                        <textarea name="description" id="description" class="form-control" cols="4" rows="10"
                                  style="width:100%;display:none">{{ old('description') }} </textarea>
                    </div>
                    @error('description')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <input type="hidden" id="inputSize" name='sizes'>
                <!-- Button trigger modal -->
                <button style="color: #1d1c1d;" type="button" class="btn bg-gradient-primary" data-bs-toggle="modal"
                        data-bs-target="#AddSizeModal">
                    Add size
                </button>
                <!-- Modal -->
                <div class="modal fade" id="AddSizeModal" tabindex="-1" aria-labelledby="AddSizeModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="AddSizeModalLabel">Add size</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body" id="AddSizeModalBody">
                            </div>
                            <div class="mt-3">
                                <button style="color: #1d1c1d;" type="button"
                                        class="btn  bg-gradient-primary btn-add-size">Add
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="input-group input-group-static">
                    <label name="group" class="ms-0">Category</label>
                    <select name="category_ids[]" class="form-control" multiple>
                        @foreach ($categories as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @endforeach
                    </select>
                    @error('category_ids')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <button style="color: #1d1c1d;" type="submit" class="btn btn-submit bg-gradient-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection
@section('style')
    <style>
        .w-40 {
            width: 40%;
        }

        .w-20 {
            width: 20%;
        }

        .ck.ck-editor {
            width: 100%;
            height: 100%;
        }

    </style>
@endsection
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"
            integrity="sha512-WFN04846sdKMIP5LKNphMaWzU7YpMyCU245etK3g/2ARYbPK9Ub18eG+ljU96qKRCWh+quCY7yefSmlkQw1ANQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{{ asset('plugin/ckeditor5-build-classic/ckeditor.js') }}"></script>
    <script>
        let sizes = [{
            id: Date.now(),
            size: 'M',
            quantity: 20,
        }];
    </script>
    <script src="{{ asset('admin/assets/js/product/product.js') }}"></script>
@endsection

demo/resources/views/admin/products/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Edit Product')
@section('content')
    <div class="card">
        <h2 style="text-align: center;padding:2px">Edit Product</h2>
        <div>
            <form action="{{ route('products.update', $product->id) }}" method="post" id="createForm"
                  enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="row">
                    <div class=" input-group-static col-5">
                        <label>Image</label>
                        <input type="file" accept="image/*" name="image" id="image-input" class="form-control">
                        @error('image')
                        <span class="text-danger"> {{ $message }}</span>
                        @enderror
                    </div>
                    <div class="col-5">
                        <img
                            src="{{ $product->images ? asset('upload/' . $product->images->first()->url) : 'upload/default.jpg' }}"
                            id="show-image" alt="Product image" width="150px" height="150px">
                    </div>
                </div>
                <div class="input-group input-group-static ">
                    <label>Name</label>
                    <input type="text" value="{{ old('name') ?? $product->name }}" name="name" class="form-control">

                    @error('name')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <div class="input-group input-group-static ">
                    <label>Price</label>
                    <input type="number" step="0.1" value="{{ old('price') ?? $product->price }}" name="price"
                           class="form-control">
                    @error('price')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <div class="input-group input-group-static ">
                    <label>Sale</label>
                    <input type="number" max="50" min="0" value="{{ old('sale') ?? $product->sale }}" name="sale"
                           class="form-control">
                    @error('sale')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <div class="description">
                        <textarea name="description" id="description" class="form-control"
                                  style="width:100%;display:none">{{ old('description') ?? $product->description }} </textarea>
                    </div>
                    @error('description')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <input type="hidden" id="inputSize" name='sizes'>
                <!-- Button trigger modal -->
                <button style="color: #1d1c1d;" type="button" class="btn bg-gradient-primary" data-bs-toggle="modal"
                        data-bs-target="#AddSizeModal">
                    Add size
                </button>
                <!-- Modal -->
                <div class="modal fade" id="AddSizeModal" tabindex="-1" aria-labelledby="AddSizeModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="AddSizeModalLabel">Add size</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body" id="AddSizeModalBody">
                            </div>
                            <div class="mt-3">
                                <button style="color: #1d1c1d;" type="button"
                                        class="btn  bg-gradient-primary btn-add-size">Add
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="input-group input-group-static ">
                    <label name="group" class="ms-0">Category</label>
                    <select name="category_ids[]" class="form-control" multiple>
                        @foreach ($categories as $item)
                            <option value="{{ $item->id }}"
                                {{ $product->categories->contains('id', $item->id) ? 'selected' : '' }}>{{ $item->name }}
                            </option>
                        @endforeach
                    </select>
                    @error('category_ids')
                    <span class="text-danger"> {{ $message }}</span>
                    @enderror
                </div>
                <button style="color: #1d1c1d;" type="submit" class="btn btn-submit bg-gradient-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection
@section('style')
    <style>
        .w-40 {
            width: 40%;
        }

        .w-20 {
            width: 20%;
        }

        .ck.ck-editor {
            width: 100%;
            height: 100%;
        }
    </style>
@endsection
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"
            integrity="sha512-WFN04846sdKMIP5LKNphMaWzU7YpMyCU245etK3g/2ARYbPK9Ub18eG+ljU96qKRCWh+quCY7yefSmlkQw1ANQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{{ asset('plugin/ckeditor5-build-classic/ckeditor.js') }}"></script>
    <script>
        let sizes = @json($product->details);
    </script>
    <script src="{{ asset('admin/assets/js/product/product.js') }}"></script>
@endsection

demo/resources/views/admin/products/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Products')
@section('content')
    <div class="card">
        <h2 style="text-align: center;padding:2px">
            Products list
        </h2>
        <div class="create d-flex">
            @can('create-product')
                <a href="{{ route('products.create') }}" class="btn btn-success btn-outline-success"><i
                        class="fa-solid fa-plus"></i></a>
            @endcan
            @if (session('message'))
                <h2 style="padding-left: 15px" class="text-primary">{{ session('message') }}</h2>
            @endif
        </div>
        <div>
            <table class="table table-hover">
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Sale</th>
                    <th>Action</th>
                </tr>
                @foreach ($products as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td><img src="{{ $item->image_path }}" width="77px" height="77px" alt=""></td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->price }}</td>
                        <td>{{ $item->sale }}</td>
                        <td class="d-flex">
                            @can('update-product')
                                <div class="edit">
                                    <a href="{{ route('products.edit', $item->id) }}"
                                       class="btn btn-outline-info btn-info"><i
                                            class="fa-solid fa-pencil"></i></a>
                                </div>
                            @endcan
                            @can('delete-product')
                                <div class="edit">
                                    <form action="{{ route('products.destroy', $item->id) }}"
                                          id="form-delete{{ $item->id }}"
                                          method="post">
                                        @csrf
                                        @method('delete')
                                    </form>
                                    <button class="btn btn-delete btn-danger btn-outline-danger"
                                            data-id={{ $item->id }}><i
                                            class="fa-solid fa-minus"></i></button>
                                </div>
                            @endcan
                            @can('show-product')
                                <a href="{{ route('products.show', $item->id) }}"
                                   class="btn btn-secondary btn-outline-secondary"><i
                                        class="fa-solid fa-eye"></i></a>
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </table>
            {{ $products->links() }}
        </div>
    </div>
@endsection
@section('script')
@endsection

demo/resources/views/admin/products/show.blade.php
@extends('admin.layouts.app')
@section('title', 'Show Product')
@section('content')
    <div class="card">
        <h2 style="text-align: center;padding:2px">Show Product</h2>
        <div>
            <div class="row">
                <div class=" ">
                    <p>Image</p>
                    <div class="col-5">
                        <img
                            src="{{ $product->images ? asset('upload/' . $product->images->first()->url) : 'upload/default.jpg' }}"
                            id="show-image" alt="Product image" width="250px" height="250px">
                    </div>
                </div>
                <div class="4">
                    <p>Name : {{ $product->name }}</p>
                </div>
                <div class="">
                    <p>Price: {{ $product->price }}</p>
                </div>
                <div class="">
                    <p>Sale: {{ $product->sale }}</p>
                </div>
                <div class="form-group">
                    <p>Description</p>
                    <div class="row w-100 h-100">
                        {!! $product->description !!}
                    </div>
                </div>
                <div>
                    <p>Size</p>
                    @if ($product->details->count() > 0)
                        @foreach ($product->details as $detail)
                            <p>Size: {{ $detail->size }} - quantity: {{ $detail->quantity }}</p>
                        @endforeach
                    @else
                        <p> This product has not entered the size</p>
                    @endif
                </div>
            </div>
            <div>
                <p>Category</p>
                @foreach ($product->categories as $item)
                    <p>{{ $item->name }}</p>
                @endforeach
            </div>
        </div>
    </div>
    </div>
@endsection